<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="neotech.ProductClientTest" tests="7" time="1.500" ignored="0" failures="0" timestamp="15 Jan 2021 09:43:52 GMT" skipped="0" hostname="DESKTOP-8H0CQOD" errors="1">
  <testcase name="testGetBadRequest" time="0.087" classname="neotech.ProductClientTest"/>
  <testcase name="testGetAllProducts" time="0.091" classname="neotech.ProductClientTest"/>
  <testcase name="testAddProduct" time="1.062" classname="neotech.ProductClientTest"/>
  <testcase name="testDeleteProduct" time="0.066" classname="neotech.ProductClientTest">
    <error type="java.lang.RuntimeException" message="304 -&gt; DELETE operation failed">
      <![CDATA[java.lang.RuntimeException: 304 -> DELETE operation failed
	at com.webapplication.service.neotech.client.ProductClient.deleteProduct(ProductClient.java:73)
	at neotech.ProductClientTest.testDeleteProduct(ProductClientTest.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testDeleteProduct -->
  <testcase name="testGetRequestNotFound" time="0.060" classname="neotech.ProductClientTest"/>
  <testcase name="testUpdateProduct" time="0.063" classname="neotech.ProductClientTest"/>
  <testcase name="testGetProduct" time="0.071" classname="neotech.ProductClientTest"/>
</testsuite> <!-- neotech.ProductClientTest -->
